const BOOKS = [
  ["창세기", "Genesis"], ["출애굽기", "Exodus"], ["레위기", "Leviticus"], ["민수기", "Numbers"], ["신명기", "Deuteronomy"],
  ["여호수아", "Joshua"], ["사사기", "Judges"], ["룻기", "Ruth"], ["사무엘상", "1Samuel"], ["사무엘하", "2Samuel"],
  ["열왕기상", "1Kings"], ["열왕기하", "2Kings"], ["역대상", "1Chronicles"], ["역대하", "2Chronicles"], ["에스라", "Ezra"],
  ["느헤미야", "Nehemiah"], ["에스더", "Esther"], ["욥기", "Job"], ["시편", "Psalms"], ["잠언", "Proverbs"],
  ["전도서", "Ecclesiastes"], ["아가", "SongofSolomon"], ["이사야", "Isaiah"], ["예레미야", "Jeremiah"], ["예레미야애가", "Lamentations"],
  ["에스겔", "Ezekiel"], ["다니엘", "Daniel"], ["호세아", "Hosea"], ["요엘", "Joel"], ["아모스", "Amos"],
  ["오바댜", "Obadiah"], ["요나", "Jonah"], ["미가", "Micah"], ["나훔", "Nahum"], ["하박국", "Habakkuk"],
  ["스바냐", "Zephaniah"], ["학개", "Haggai"], ["스가랴", "Zechariah"], ["말라기", "Malachi"],
  ["마태복음", "Matthew"], ["마가복음", "Mark"], ["누가복음", "Luke"], ["요한복음", "John"], ["사도행전", "Acts"],
  ["로마서", "Romans"], ["고린도전서", "1Corinthians"], ["고린도후서", "2Corinthians"], ["갈라디아서", "Galatians"], ["에베소서", "Ephesians"],
  ["빌립보서", "Philippians"], ["골로새서", "Colossians"], ["데살로니가전서", "1Thessalonians"], ["데살로니가후서", "2Thessalonians"],
  ["디모데전서", "1Timothy"], ["디모데후서", "2Timothy"], ["디도서", "Titus"], ["빌레몬서", "Philemon"], ["히브리서", "Hebrews"],
  ["야고보서", "James"], ["베드로전서", "1Peter"], ["베드로후서", "2Peter"], ["요한일서", "1John"], ["요한이서", "2John"],
  ["요한삼서", "3John"], ["유다서", "Jude"], ["요한계시록", "Revelation"]
].map(([ko, file], index) => ({ ko, file, index, testament: index < 39 ? "old" : "new" }));

const TRANSLATIONS = { krv1961: { id: "krv1961", name: "개역한글", source: "https://raw.githubusercontent.com/bluesaurel/Korean-Bible-1961-KRV/main/data/", attribution: "대한성서공회" } };
const $ = (selector) => document.querySelector(selector);
const bookSelect = $("#bookSelect"), chapterSelect = $("#chapterSelect"), chapterTitle = $("#chapterTitle"), versesEl = $("#verses"), statusEl = $("#status");
// Top/side chapter arrows were intentionally removed. Keep only controls that actually exist.
const prevButtons = [$("#prevChapter"), $("#prevChapterBottom")].filter(Boolean);
const nextButtons = [$("#nextChapter"), $("#nextChapterBottom")].filter(Boolean);
const testamentButtons = [...document.querySelectorAll(".testament-button")];
const searchForm = $("#searchForm"), searchInput = $("#searchInput"), searchButton = $("#searchButton"), searchPanel = $("#searchPanel"), searchSummary = $("#searchSummary"), searchResults = $("#searchResults");
const cache = new Map(); const SEARCH_LIMIT = 100, SEARCH_BATCH_SIZE = 6;
let state = restoreLocation(), currentBookData = null, activeTestament = "all", searchRun = 0;
function restoreLocation(){try{const s=JSON.parse(localStorage.getItem("bible-reader-location"));if(s&&Number.isInteger(s.bookIndex)&&Number.isInteger(s.chapter))return{bookIndex:Math.max(0,Math.min(BOOKS.length-1,s.bookIndex)),chapter:Math.max(1,s.chapter)}}catch(_){}return{bookIndex:BOOKS.findIndex(b=>b.file==="John"),chapter:3}}
function saveLocation(){localStorage.setItem("bible-reader-location",JSON.stringify(state))}
function booksForTestament(t=activeTestament){return t==="all"?BOOKS:BOOKS.filter(b=>b.testament===t)}
function updateTestamentButtons(){testamentButtons.forEach(b=>{const a=b.dataset.testament===activeTestament;b.classList.toggle("active",a);b.setAttribute("aria-pressed",String(a))})}
function setupBookSelect(){bookSelect.innerHTML="";booksForTestament().forEach(book=>{const o=document.createElement("option");o.value=book.index;o.textContent=book.ko;bookSelect.append(o)});bookSelect.value=String(state.bookIndex)}
function ensureBookVisible(){const b=BOOKS[state.bookIndex];if(activeTestament!=="all"&&b.testament!==activeTestament){activeTestament="all";updateTestamentButtons();setupBookSelect()}}
async function setTestament(t){if(!["all","old","new"].includes(t)||t===activeTestament)return;activeTestament=t;updateTestamentButtons();const v=booksForTestament();if(!v.some(b=>b.index===state.bookIndex)){state.bookIndex=v[0].index;state.chapter=1;setupBookSelect();await loadCurrent();return}setupBookSelect()}
async function fetchBook(book){if(cache.has(book.file))return cache.get(book.file);const r=await fetch(`${TRANSLATIONS.krv1961.source}${book.file}.json`,{cache:"force-cache"});if(!r.ok)throw new Error(`${book.ko} 본문을 불러오지 못했습니다.`);const d=await r.json();cache.set(book.file,d);return d}
function setupChapterSelect(data){chapterSelect.innerHTML="";const count=data.chapters.length;for(let c=1;c<=count;c++){const o=document.createElement("option");o.value=c;o.textContent=`${c}장`;chapterSelect.append(o)}state.chapter=Math.max(1,Math.min(count,state.chapter));chapterSelect.value=String(state.chapter)}
function setLoading(m="본문을 불러오는 중…"){statusEl.hidden=false;statusEl.classList.remove("error");statusEl.textContent=m;versesEl.innerHTML=""}
function setError(m){statusEl.hidden=false;statusEl.classList.add("error");statusEl.textContent=m}
function updateNavigationState(data=currentBookData){if(!data)return;const count=data.chapters.length,atStart=state.bookIndex===0&&state.chapter===1,atEnd=state.bookIndex===BOOKS.length-1&&state.chapter===count;prevButtons.forEach(b=>{b.disabled=atStart;b.setAttribute("aria-disabled",String(atStart))});nextButtons.forEach(b=>{b.disabled=atEnd;b.setAttribute("aria-disabled",String(atEnd))})}
function renderVerses(data){const book=BOOKS[state.bookIndex],chapter=data.chapters.find(i=>Number(i.chapter)===state.chapter);chapterTitle.textContent=`${book.ko} ${state.chapter}장`;document.title=`${book.ko} ${state.chapter}장 · 성경 읽기`;if(!chapter){setError("해당 장을 찾지 못했습니다.");return}const f=document.createDocumentFragment();chapter.verses.forEach(v=>{const p=document.createElement("p");p.className="verse";p.dataset.verse=v.verse;const n=document.createElement("span");n.className="verse-number";n.textContent=v.verse;const t=document.createElement("span");t.className="verse-text";t.textContent=v.text;t.title="클릭하면 이 절을 복사합니다";t.addEventListener("click",()=>copyVerse(p,v));p.append(n,t);f.append(p)});statusEl.hidden=true;versesEl.replaceChildren(f);updateNavigationState(data)}
async function copyVerse(el,v){const b=BOOKS[state.bookIndex],copyText=`${b.ko} ${state.chapter}:${v.verse}\n${v.text}`;try{await navigator.clipboard.writeText(copyText)}catch(_){const ta=document.createElement("textarea");ta.value=copyText;document.body.append(ta);ta.select();document.execCommand("copy");ta.remove()}el.classList.add("copied");setTimeout(()=>el.classList.remove("copied"),900)}
async function loadCurrent({scrollTop=true}={}){ensureBookVisible();const book=BOOKS[state.bookIndex];bookSelect.value=String(state.bookIndex);setLoading();try{currentBookData=await fetchBook(book);setupChapterSelect(currentBookData);renderVerses(currentBookData);saveLocation();if(scrollTop)window.scrollTo({top:0,behavior:"auto"})}catch(e){console.error(e);setError("본문을 불러오지 못했습니다. 인터넷 연결을 확인한 뒤 다시 시도해 주세요.")}}
async function moveChapter(delta){if(!currentBookData)return;const count=currentBookData.chapters.length,next=state.chapter+delta;if(next>=1&&next<=count){state.chapter=next;chapterSelect.value=String(next);renderVerses(currentBookData);saveLocation();window.scrollTo({top:0,behavior:"smooth"});return}const ni=state.bookIndex+(delta>0?1:-1);if(ni<0||ni>=BOOKS.length)return;state.bookIndex=ni;state.chapter=delta>0?1:999;await loadCurrent()}
function renderSearchResults(results,q,failed){searchResults.innerHTML="";searchPanel.hidden=false;if(!results.length){searchSummary.textContent=`“${q}” 검색 결과가 없습니다.${failed?` (${failed}권 로딩 실패)`:""}`;return}const limited=results.length>=SEARCH_LIMIT;searchSummary.textContent=`“${q}” ${results.length}${limited?"+":""}개 결과${failed?` · ${failed}권 로딩 실패`:""}`;const f=document.createDocumentFragment();results.slice(0,SEARCH_LIMIT).forEach(r=>{const b=document.createElement("button");b.type="button";b.className="search-result";const ref=document.createElement("strong");ref.textContent=`${r.book.ko} ${r.chapter}:${r.verse}`;const t=document.createElement("span");t.textContent=r.text;b.append(ref,t);b.addEventListener("click",()=>goToSearchResult(r));f.append(b)});searchResults.append(f)}
async function searchBible(q){const normalized=q.trim().toLocaleLowerCase("ko-KR");if(!normalized)return;const run=++searchRun;searchPanel.hidden=false;searchResults.innerHTML="";searchSummary.textContent=`“${q.trim()}” 검색 준비 중…`;searchButton.disabled=true;searchInput.disabled=true;const results=[];let failed=0;try{for(let start=0;start<BOOKS.length&&results.length<SEARCH_LIMIT;start+=SEARCH_BATCH_SIZE){if(run!==searchRun)return;const batch=BOOKS.slice(start,start+SEARCH_BATCH_SIZE);searchSummary.textContent=`“${q.trim()}” 검색 중… ${Math.min(start+batch.length,BOOKS.length)}/${BOOKS.length}권`;const loaded=await Promise.all(batch.map(async book=>{try{return{book,data:await fetchBook(book)}}catch(e){console.error(e);failed++;return null}}));loaded.filter(Boolean).forEach(({book,data})=>{if(results.length>=SEARCH_LIMIT)return;data.chapters.forEach(ch=>{if(results.length>=SEARCH_LIMIT)return;ch.verses.forEach(v=>{if(results.length>=SEARCH_LIMIT)return;if(String(v.text).toLocaleLowerCase("ko-KR").includes(normalized))results.push({book,chapter:Number(ch.chapter),verse:Number(v.verse),text:v.text})})})})}if(run===searchRun)renderSearchResults(results,q.trim(),failed)}finally{if(run===searchRun){searchButton.disabled=false;searchInput.disabled=false;searchInput.focus()}}}
async function goToSearchResult(r){state.bookIndex=r.book.index;state.chapter=r.chapter;await loadCurrent();searchPanel.hidden=true;requestAnimationFrame(()=>{const t=versesEl.querySelector(`[data-verse="${r.verse}"]`);if(!t)return;t.classList.add("searched");t.scrollIntoView({behavior:"smooth",block:"center"});setTimeout(()=>t.classList.remove("searched"),1800)})}
function setupControls(){bookSelect.addEventListener("change",async()=>{state.bookIndex=Number(bookSelect.value);state.chapter=1;await loadCurrent()});chapterSelect.addEventListener("change",()=>{state.chapter=Number(chapterSelect.value);renderVerses(currentBookData);saveLocation();window.scrollTo({top:0,behavior:"smooth"})});testamentButtons.forEach(b=>b.addEventListener("click",()=>setTestament(b.dataset.testament)));prevButtons.forEach(b=>b.addEventListener("click",()=>moveChapter(-1)));nextButtons.forEach(b=>b.addEventListener("click",()=>moveChapter(1)));$("#fontDown")?.addEventListener("click",()=>changeFont(-1));$("#fontUp")?.addEventListener("click",()=>changeFont(1));$("#widthToggle")?.addEventListener("click",toggleWidth);$("#themeToggle")?.addEventListener("click",toggleTheme);searchForm.addEventListener("submit",e=>{e.preventDefault();searchBible(searchInput.value)});$("#closeSearch")?.addEventListener("click",()=>{searchRun++;searchPanel.hidden=true;searchButton.disabled=false;searchInput.disabled=false});document.addEventListener("keydown",e=>{const tag=document.activeElement?.tagName;if(["INPUT","TEXTAREA","SELECT"].includes(tag))return;if(e.key==="ArrowLeft"){e.preventDefault();moveChapter(-1)}if(e.key==="ArrowRight"){e.preventDefault();moveChapter(1)}if(e.key==="/"){e.preventDefault();searchInput.focus()}})}
function restoreReadingPreferences(){const fs=Number(localStorage.getItem("bible-reader-font-size"))||21;document.documentElement.style.setProperty("--font-size",`${fs}px`);const w=localStorage.getItem("bible-reader-width")||"860";document.documentElement.style.setProperty("--reader-width",`${w}px`);const saved=localStorage.getItem("bible-reader-theme"),dark=window.matchMedia("(prefers-color-scheme: dark)").matches;document.documentElement.dataset.theme=saved||(dark?"dark":"light")}
function changeFont(d){const raw=getComputedStyle(document.documentElement).getPropertyValue("--font-size"),cur=parseFloat(raw)||21,next=Math.max(16,Math.min(32,cur+d));document.documentElement.style.setProperty("--font-size",`${next}px`);localStorage.setItem("bible-reader-font-size",String(next))}
function toggleWidth(){const cur=localStorage.getItem("bible-reader-width")||"860",next=cur==="860"?"1080":cur==="1080"?"720":"860";document.documentElement.style.setProperty("--reader-width",`${next}px`);localStorage.setItem("bible-reader-width",next)}
function toggleTheme(){const next=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=next;localStorage.setItem("bible-reader-theme",next)}
restoreReadingPreferences();updateTestamentButtons();setupBookSelect();setupControls();loadCurrent({scrollTop:false});