(() => {
  const toggle=document.querySelector("#compareToggle"),panel=document.querySelector("#comparePanel"),rows=document.querySelector("#compareRows"),compareStatus=document.querySelector("#compareStatus"),singleReader=document.querySelector("#singleReader"),bookSelect=document.querySelector("#bookSelect"),chapterSelect=document.querySelector("#chapterSelect"),chapterTitle=document.querySelector("#chapterTitle"),leftSelect=document.querySelector("#leftTranslation"),rightSelect=document.querySelector("#rightTranslation"),swapButton=document.querySelector("#swapTranslations"),leftName=document.querySelector("#leftTranslationName"),leftMeta=document.querySelector("#leftTranslationMeta"),rightName=document.querySelector("#rightTranslationName"),rightMeta=document.querySelector("#rightTranslationMeta"),sideButton=document.querySelector("#compareSideBySide"),stackButton=document.querySelector("#compareStacked");
  if(!toggle||!panel||!rows||!singleReader||!leftSelect||!rightSelect||typeof TRANSLATIONS==="undefined"||typeof fetchBook!=="function")return;
  let enabled=localStorage.getItem("bible-reader-compare")==="true",viewMode=localStorage.getItem("bible-reader-compare-view")==="stacked"?"stacked":"side",renderToken=0;
  function fillOptions(){[leftSelect,rightSelect].forEach(select=>{select.innerHTML="";Object.values(TRANSLATIONS).forEach(tr=>{const o=document.createElement("option");o.value=tr.id;o.textContent=tr.name;select.append(o)})});const savedLeft=localStorage.getItem("bible-reader-compare-left"),savedRight=localStorage.getItem("bible-reader-compare-right");leftSelect.value=TRANSLATIONS[savedLeft]?savedLeft:(typeof activeTranslationId!=="undefined"?activeTranslationId:"krv1961");rightSelect.value=TRANSLATIONS[savedRight]?savedRight:(leftSelect.value==="kjv"?"web":"kjv");if(leftSelect.value===rightSelect.value)rightSelect.value=Object.keys(TRANSLATIONS).find(id=>id!==leftSelect.value)||leftSelect.value}
  function metaFor(id){const tr=TRANSLATIONS[id];return tr?`${tr.language} · ${tr.rights}`:""}
  function syncHeader(){const l=TRANSLATIONS[leftSelect.value],r=TRANSLATIONS[rightSelect.value];leftName.textContent=l?.name||"";leftMeta.textContent=metaFor(leftSelect.value);rightName.textContent=r?.name||"";rightMeta.textContent=metaFor(rightSelect.value);localStorage.setItem("bible-reader-compare-left",leftSelect.value);localStorage.setItem("bible-reader-compare-right",rightSelect.value)}
  function applyViewMode(){const stacked=viewMode==="stacked";panel.classList.toggle("stacked",stacked);sideButton?.classList.toggle("active",!stacked);stackButton?.classList.toggle("active",stacked);sideButton?.setAttribute("aria-pressed",String(!stacked));stackButton?.setAttribute("aria-pressed",String(stacked));localStorage.setItem("bible-reader-compare-view",viewMode)}
  async function getVerses(id,bookIndex,chapter){const book=BOOKS[bookIndex];if(!book)return[];const data=await fetchBook(book,id);const ch=data.chapters.find(x=>Number(x.chapter)===chapter);return(ch?.verses||[]).map(v=>({verse:Number(v.verse),text:v.text}))}
  function cellClass(id){const lang=TRANSLATIONS[id]?.language||"";return /^English|Français|Deutsch|Latina|Русский/.test(lang)?" compare-english":""}
  async function renderCompare(){if(!enabled)return;const token=++renderToken,bookIndex=Number(bookSelect.value),chapter=Number(chapterSelect.value);if(!Number.isInteger(bookIndex)||!chapter)return;syncHeader();compareStatus.textContent="비교 역본을 불러오는 중…";compareStatus.hidden=false;rows.replaceChildren();try{const[leftVerses,rightVerses]=await Promise.all([getVerses(leftSelect.value,bookIndex,chapter),getVerses(rightSelect.value,bookIndex,chapter)]);if(token!==renderToken||!enabled)return;if(!leftVerses.length||!rightVerses.length)throw new Error("비교할 장을 찾지 못했습니다.");const lm=new Map(leftVerses.map(v=>[v.verse,v.text])),rm=new Map(rightVerses.map(v=>[v.verse,v.text])),nums=[...new Set([...lm.keys(),...rm.keys()])].sort((a,b)=>a-b),f=document.createDocumentFragment();nums.forEach(n=>{const row=document.createElement("div");row.className="compare-row";row.dataset.verse=n;const lc=document.createElement("div"),rc=document.createElement("div");lc.className=`compare-cell${cellClass(leftSelect.value)}`;rc.className=`compare-cell${cellClass(rightSelect.value)}`;[lc,rc].forEach((cell,i)=>{const no=document.createElement("span"),txt=document.createElement("span");no.className="compare-verse-number";no.textContent=n;txt.textContent=(i?rm:lm).get(n)||"—";cell.append(no,txt)});row.append(lc,rc);f.append(row)});rows.replaceChildren(f);compareStatus.hidden=true}catch(error){console.error(error);compareStatus.textContent="비교 역본을 불러오지 못했습니다. 잠시 후 다시 시도해 주세요."}}
  function keepDifferent(changed){if(leftSelect.value!==rightSelect.value)return;const other=Object.keys(TRANSLATIONS).find(id=>id!==leftSelect.value);if(changed==="left")rightSelect.value=other;else leftSelect.value=other}
  function applyMode(){toggle.classList.toggle("active",enabled);toggle.setAttribute("aria-pressed",String(enabled));panel.hidden=!enabled;singleReader.hidden=enabled;localStorage.setItem("bible-reader-compare",String(enabled));if(enabled)renderCompare()}
  fillOptions();applyViewMode();toggle.addEventListener("click",()=>{enabled=!enabled;applyMode()});leftSelect.addEventListener("change",()=>{keepDifferent("left");renderCompare()});rightSelect.addEventListener("change",()=>{keepDifferent("right");renderCompare()});swapButton?.addEventListener("click",()=>{const l=leftSelect.value;leftSelect.value=rightSelect.value;rightSelect.value=l;renderCompare()});sideButton?.addEventListener("click",()=>{viewMode="side";applyViewMode()});stackButton?.addEventListener("click",()=>{viewMode="stacked";applyViewMode()});const observer=new MutationObserver(()=>{if(enabled)requestAnimationFrame(renderCompare)});observer.observe(chapterTitle,{childList:true,subtree:true,characterData:true});syncHeader();applyMode();
})();